-- total revenue generated by male and female customers
SELECT gender,SUM(purchase_amount) AS Revenue 
FROM mytable 
GROUP BY gender;

-- which customer used a discount but still spent more than the average purchase amount
SELECT customer_id,purchase_amount 
FROM mytable
WHERE discount_applied='YES'
AND purchase_amount>=(SELECT AVG(purchase_amount) FROM mytable);

-- which are the top 5 products with the highest average reveiw rating
SELECT item_purchased,AVG(review_rating) AS "Average review rating"
FROM mytable 
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- campare the average purchase amount between standard and express shipping
SELECT shipping_type,ROUND(AVG(purchase_amount),2) AS "Average purchase Amount"
FROM mytable
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

SELECT subscription_status,
	COUNT(customer_id) AS 'total_Customer',
	ROUND(AVG(purchase_amount),2) AS 'Average_Spent',
    SUM(purchase_amount) AS 'total_revenue'
FROM mytable
GROUP BY subscription_status
ORDER BY total_revenue,Average_Spent DESC;

-- WHICH 5 PRODUCTS HAVE THE HIGH PERCENTAGE OF PURCHASES WITH DISCOUNT APPLIED
SELECT item_purchased as 'product',
	ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM mytable
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- segment customers into New,Returning and loyal based on their total no of previous purchase and show the count of each segment
WITH customer_type AS (SELECT customer_id,previous_purchases,
CASE 
	WHEN previous_purchases=1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
    FROM mytable
    )
    SELECT customer_segment ,count(*) as "No_of_customers"
    FROM customer_type
    GROUP BY customer_segment;
    
    -- what are the  top 3 product purchased in each category
    WITH item_count AS(
    SELECT category,item_purchased,
    COUNT(customer_id) AS total_orders,
    ROW_NUMBER() OVER( PARTITION BY category ORDER BY COUNT(customer_id )DESC) AS item_rank
    FROM mytable
    GROUP BY category,item_purchased
    )
    SELECT item_rank,category,item_purchased,total_orders
    FROM mytable	
    WHERE item_rank<=3;
   
   -- Are customers who are repeat buyers(more than 5 previous purchases) are likely to subscribe?
   SELECT subscription_status,COUNT(customer_id) AS 'repeat_buyers'
   FROM mytable
   WHERE previous_purchases>5
   GROUP BY subscription_status;
   
   -- what is the revenue contribution of each age group
   SELECT age_group,SUM(purchase_amount) AS 'revenue'
   FROM mytable
   GROUP BY age_group
	ORDER BY revenue DESC ;
   